package com.yoziming.book.pojo;

import java.math.BigDecimal;
import java.util.Objects;
import java.util.StringJoiner;

public class OrderItem {
    private int id;
    private String name;
    private int count;
    private BigDecimal price;
    private BigDecimal totalPrice;
    private String orderId;

    public OrderItem() {
    }

    // region Constructor, getters, setters, equals, hashCode, toString, builder -- generated by BoB the Builder of
    // Beans

    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    public OrderItem(String name, int count, BigDecimal price, BigDecimal totalPrice, String orderId) {
        this.name = Objects.requireNonNull(name);
        this.count = count;
        this.price = Objects.requireNonNull(price);
        this.totalPrice = Objects.requireNonNull(totalPrice);
        this.orderId = Objects.requireNonNull(orderId);
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = Objects.requireNonNull(name);
    }

    public int getCount() {
        return count;
    }

    public void setCount(int count) {
        this.count = count;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = Objects.requireNonNull(price);
    }

    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = Objects.requireNonNull(totalPrice);
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = Objects.requireNonNull(orderId);
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        OrderItem that = (OrderItem) o;

        return Objects.equals(this.getId(), that.getId()) && Objects.equals(this.getName(), that.getName()) && Objects.equals(this.getCount(), that.getCount()) && Objects.equals(this.getPrice(), that.getPrice()) && Objects.equals(this.getTotalPrice(), that.getTotalPrice()) && Objects.equals(this.getOrderId(), that.getOrderId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getName(), getCount(), getPrice(), getTotalPrice(), getOrderId());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("id=" + getId())
                .add("name=" + getName())
                .add("count=" + getCount())
                .add("price=" + getPrice())
                .add("totalPrice=" + getTotalPrice())
                .add("orderId=" + getOrderId())
                .toString();
    }// endregion toString()

    // region Builder -- generated by BoB the Builder of Beans
    public static OrderItem.Builder builder() {
        return new OrderItem.Builder();
    }

    public static OrderItem.Builder builder(OrderItem data) {
        return new OrderItem.Builder(data);
    }

    public static final class Builder {

        private int id;
        private String name;
        private int count;
        private BigDecimal price;
        private BigDecimal totalPrice;
        private String orderId;

        private Builder() {
        }

        private Builder(OrderItem initialData) {
            this.id = initialData.id;
            this.name = initialData.name;
            this.count = initialData.count;
            this.price = initialData.price;
            this.totalPrice = initialData.totalPrice;
            this.orderId = initialData.orderId;
        }

        public Builder setId(int id) {
            this.id = id;
            return this;
        }

        public Builder setName(String name) {
            this.name = name;
            return this;
        }

        public Builder setCount(int count) {
            this.count = count;
            return this;
        }

        public Builder setPrice(BigDecimal price) {
            this.price = price;
            return this;
        }

        public Builder setTotalPrice(BigDecimal totalPrice) {
            this.totalPrice = totalPrice;
            return this;
        }

        public Builder setOrderId(String orderId) {
            this.orderId = orderId;
            return this;
        }

    }// endregion Builder
    // endregion Constructor, getters, setters, equals, hashCode, toString, builder
}
