package com.yoziming.book.pojo;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;
import java.util.StringJoiner;

public class Order {
    private String orderId;
    private Date createTime;
    private BigDecimal price;
    // 0=未發貨, 1=已發, 2=已收到
    private int status = 0;

    public Order() {
    }

    private int userId;

    // region Constructor, getters, setters, equals, hashCode, toString, builder -- generated by BoB the Builder of
    // Beans

    // The code below has been generated by BoB the Builder of Beans based on the class' fields.
    // Everything after this comment will be regenerated if you invoke BoB again.
    // If you don't know who BoB is, you can find him here: https://bitbucket.org/atlassianlabs/bob-the-builder-of-beans

    public Order(String orderId, Date createTime, BigDecimal price, int status, int userId) {
        this.orderId = Objects.requireNonNull(orderId);
        this.createTime = Objects.requireNonNull(createTime);
        this.price = Objects.requireNonNull(price);
        this.status = status;
        this.userId = userId;
    }

    // region Getters and setters -- generated by BoB the Builder of Beans
    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = Objects.requireNonNull(orderId);
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = Objects.requireNonNull(createTime);
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = Objects.requireNonNull(price);
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }// endregion Getters and setters

    // region hashCode() and equals() -- generated by BoB the Builder of Beans
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Order that = (Order) o;

        return Objects.equals(this.getOrderId(), that.getOrderId()) && Objects.equals(this.getCreateTime(),
                that.getCreateTime()) && Objects.equals(this.getPrice(), that.getPrice()) && Objects.equals(this.getStatus(), that.getStatus()) && Objects.equals(this.getUserId(), that.getUserId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrderId(), getCreateTime(), getPrice(), getStatus(), getUserId());
    }// endregion hashCode() and equals()

    // region toString() -- generated by BoB the Builder of Beans
    @Override
    public String toString() {
        return new StringJoiner(", ", this.getClass().getSimpleName() + "{", "}")
                .add("orderId=" + getOrderId())
                .add("createTime=" + getCreateTime())
                .add("price=" + getPrice())
                .add("status=" + getStatus())
                .add("userId=" + getUserId())
                .toString();
    }// endregion toString()

    // region Builder -- generated by BoB the Builder of Beans
    public static Order.Builder builder() {
        return new Order.Builder();
    }

    public static Order.Builder builder(Order data) {
        return new Order.Builder(data);
    }

    public static final class Builder {

        private String orderId;
        private Date createTime;
        private BigDecimal price;
        private int status;
        private int userId;

        private Builder() {
        }

        private Builder(Order initialData) {
            this.orderId = initialData.orderId;
            this.createTime = initialData.createTime;
            this.price = initialData.price;
            this.status = initialData.status;
            this.userId = initialData.userId;
        }

        public Builder setOrderId(String orderId) {
            this.orderId = orderId;
            return this;
        }

        public Builder setCreateTime(Date createTime) {
            this.createTime = createTime;
            return this;
        }

        public Builder setPrice(BigDecimal price) {
            this.price = price;
            return this;
        }

        public Builder setStatus(int status) {
            this.status = status;
            return this;
        }

        public Builder setUserId(int userId) {
            this.userId = userId;
            return this;
        }

        public Order build() {
            return new Order(orderId, createTime, price, status, userId);
        }
    }// endregion Builder
    // endregion Constructor, getters, setters, equals, hashCode, toString, builder
}
